### ISSUE TITLE
Masamune (lisp machine)

### ISSUE THREAD

**Issue by gabriel-laddel** [stacksmith/cl-fm#1]
Masamune, my lisp-only (including graphics - via CLIM) linux distro running on a well-specified set of hardware (hence, one knows code written on it will ALWAYS work on other machines) is now for sale. It is hands down the best computing environment in the galaxy.

CL-GTK is well-intentioned, but misguided.

Respond for further details.

**Comment by stacksmith** [comment]
OK, you have my attention.  More info?
